version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: echo-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  app:
    build: .
    # ports:
    #   - 8080:80
    volumes:
      - ..:/workspace
    command: sleep infinity
